// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed-users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedUser = `-- name: CreateFeedUser :one
WITH insert_feed_user AS (
    INSERT INTO feed_follow(id, user_id, feed_id)
    VALUES($1, $2, $3)
    RETURNING id, user_id, feed_id, created_at, updated_at
)
SELECT ifu.id, ifu.user_id, ifu.feed_id, ifu.created_at, ifu.updated_at,
    u.name AS user_name,
    f.name AS feed_name
FROM insert_feed_user ifu
    JOIN users u ON ifu.user_id = u.id
    JOIN feed f ON ifu.feed_id = f.id
`

type CreateFeedUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	FeedID uuid.UUID
}

type CreateFeedUserRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserName  string
	FeedName  string
}

func (q *Queries) CreateFeedUser(ctx context.Context, arg CreateFeedUserParams) (CreateFeedUserRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedUser, arg.ID, arg.UserID, arg.FeedID)
	var i CreateFeedUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.FeedName,
	)
	return i, err
}

const deleteFeedUser = `-- name: DeleteFeedUser :exec
DELETE FROM feed_follow
WHERE user_id = $1
    AND feed_id = $2
`

type DeleteFeedUserParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeleteFeedUser(ctx context.Context, arg DeleteFeedUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedUser, arg.UserID, arg.FeedID)
	return err
}

const getFollowingFeeds = `-- name: GetFollowingFeeds :many
SELECT f.name AS feed_name,
    f.url AS feed_url,
    u.name AS user_name
FROM feed_follow ff
    JOIN users u ON ff.user_id = u.id
    JOIN feed f ON ff.feed_id = f.id
WHERE ff.user_id = $1
`

type GetFollowingFeedsRow struct {
	FeedName string
	FeedUrl  string
	UserName string
}

func (q *Queries) GetFollowingFeeds(ctx context.Context, userID uuid.UUID) ([]GetFollowingFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowingFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingFeedsRow
	for rows.Next() {
		var i GetFollowingFeedsRow
		if err := rows.Scan(&i.FeedName, &i.FeedUrl, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
